name: fun_generator
description: A code generation tool for something I haven't decided yet
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  build: ^2.4.1
  code_builder: ^4.6.0
  dart_style: 2.3.2
  build_config: ^1.1.1
  analyzer: ^6.2.0
  meta: ^1.9.1
  source_gen: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: 2.4.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

